puts "The students of Villains Academy"
puts "----------------------"
puts "Dr. Hannibal Lecter"
puts "Darth Vader"
puts "Nurse Ratched"
puts "Michael Corleone"
puts "Lucien LaChance"
puts "Alex DeLarge"
puts "The Wicked Witch of the West"
puts "Terminator"
puts "The Joker"
puts "Freddy Kruger"
puts "Jeoffrey Baratheon"
puts "Norman Bates"

print "There are "
print "12"
print " students."  
